type Swap @entity {
  id: ID!
  sender: String!
  amount0In: BigInt!
  amount1In: BigInt!
  amount0Out: BigInt!
  amount1Out: BigInt!
  to: String!
  blockNumber: BigInt!
  timestamp: BigInt!
  transactionHash: String!
  contractAddress: String!
}

type Mint @entity {
  id: ID!
  sender: String!
  amount0: BigInt!
  amount1: BigInt!
  blockNumber: BigInt!
  timestamp: BigInt!
  transactionHash: String!
  contractAddress: String!
}

type Burn @entity {
  id: ID!
  sender: String!
  amount0: BigInt!
  amount1: BigInt!
  to: String!
  blockNumber: BigInt!
  timestamp: BigInt!
  transactionHash: String!
  contractAddress: String!
}
