type TotalETHStakedUpdated @entity {
  id: ID!
  totalETHStaked: BigInt!
  blockNumber: BigInt!
  timestamp: BigInt!
  transactionHash: String!
  contractAddress: String!
}

type RewardsProcessed @entity {
  id: ID!
  totalRewards: BigInt!
  elRewards: BigInt!
  clRewards: BigInt!
  netRewards: BigInt!
  fees: BigInt!
  blockNumber: BigInt!
  timestamp: BigInt!
  transactionHash: String!
  contractAddress: String!
}

type EthWithdrawn @entity {
  id: ID!
  to: String!
  amount: BigInt!
  blockNumber: BigInt!
  timestamp: BigInt!
  transactionHash: String!
  contractAddress: String!
}
