type Deposit @entity {
  id: ID!
  caller: String!
  owner: String!
  assets: BigInt!
  shares: BigInt!
  blockNumber: BigInt!
  timestamp: BigInt!
  transactionHash: String!
  contractAddress: String!
}

type Withdraw @entity {
  id: ID!
  caller: String!
  receiver: String!
  owner: String!
  assets: BigInt!
  shares: BigInt!
  blockNumber: BigInt!
  timestamp: BigInt!
  transactionHash: String!
  contractAddress: String!
}

type Transfer @entity {
  id: ID!
  from: String!
  to: String!
  value: BigInt!
  blockNumber: BigInt!
  timestamp: BigInt!
  transactionHash: String!
  contractAddress: String!
}
